pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'TCC-TRANSACIONT首页'
   keywords: 'tcc，分布式事务'
   description: '一款开源的微服务架构下的TCC型分布式事务解决方案，致力于提供高性能和简单易用的分布式事务服务。'
  # home config
  en-us:
   title: 'TCC-TRANSACIONT HOME'
   keywords: 'tcc'
   description: ''
 community:
  # 社区页配置
  zh-cn:
   title: 'TCC-TRANSACIONT社区'
   keywords: 'tcc，分布式事务'
   description: '一款开源的微服务架构下的TCC型分布式事务解决方案，致力于提供高性能和简单易用的分布式事务服务。'
  # community page config
  en-us:
   title: 'TCC-TRANSACIONT COMMUNITY'
   keywords: 'tcc'
   description: ''
 blog:
  # 博客列表页配置
  zh-cn:
   title: 'TCC-TRANSACIONT博客'
   keywords: 'tcc，分布式事务'
   description: '一款开源的微服务架构下的TCC型分布式事务解决方案，致力于提供高性能和简单易用的分布式事务服务。'
  en-us:
   # blog list page config
   title: 'TCC-TRANSACIONT BLOG'
   keywords: 'tcc'
   description: ''
